title: Regex Extractor
description: >-
  This will return a JSON file of all strings the given regex matches in
  the selected files
type: object
documents:
  - selected
properties:
  regex:
    type: array
    default: [""]
    items:
      title: Regex
      type: string
      format: regex
required: [regex]
